name: Deploy MultiDockeR
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    environment: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Login to Docker Hub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ofirifo/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ofirifo/react-test npm test

      - run: docker build -t ofirifo/multi-client ./client
      - run: docker build -t ofirifo/multi-nginx ./nginx
      - run: docker build -t ofirifo/multi-server ./server
      - run: docker build -t ofirifo/multi-worker ./worker

      - run: docker push ofirifo/multi-client
      - run: docker push ofirifo/multi-nginx
      - run: docker push ofirifo/multi-server
      - run: docker push ofirifo/multi-worker
